### ISSUE TITLE
Doesn't build with bindgen 0.71.1

### ISSUE THREAD

**Issue by DavidVentura** [Tomin1/oggopus-embedded#3]
Hi
Trying to test out opus-embedded 0.1.1 but it doesn't build.
```
$ rustc --version
rustc 1.87.0 (17067e9ac 2025-05-09)
```
```
error[E0599]: no function or associated item named `c_string` found for struct `proc_macro2::Literal` in the current scope
    --> /home/david/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bindgen-0.71.1/codegen/mod.rs:734:62
     |
734  | ...                   let cstr = proc_macro2::Literal::c_string(cstr);
     |                                                        ^^^^^^^^ function or associated item not found in `Literal`
     |
note: if you're trying to build a new `proc_macro2::Literal` consider using one of the following associated functions:
      proc_macro2::Literal::u8_suffixed
      proc_macro2::Literal::u16_suffixed
      proc_macro2::Literal::u32_suffixed
      proc_macro2::Literal::u64_suffixed
      and 28 others
    --> /home/david/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proc-macro2-1.0.78/src/lib.rs:1124:5
     |
1124 | /     suffixed_int_literals! {
1125 | |         u8_suffixed => u8,
1126 | |         u16_suffixed => u16,
1127 | |         u32_suffixed => u32,
...    |
1136 | |         isize_suffixed => isize,
1137 | |     }
     | |_____^
     = note: this error originates in the macro `suffixed_int_literals` (in Nightly builds, run with -Z macro-backtrace for more info)
help: there is an associated function `string` with a similar name
     |
734  -                             let cstr = proc_macro2::Literal::c_string(cstr);
734  +                             let cstr = proc_macro2::Literal::string(cstr);
     |
```

bumping `bindgen` to 0.72.0 works.

The build system also requires to have installed `autoconf` and `libtool`

**Comment by Tomin1** [comment]
Interesting. What target did you build it for? I typically use `thumbv6m-none-eabi` and that's fine also with bindgen 0.71.1.
